Design patterns
Ivanenko16/AMPBFramework pull request #1
Opened 2022-02-15 09:20 UTC by Ivanenko16

2022-02-15 20:52 UTC, ivanmatiashepam requested changes

2022-02-15 20:52 UTC, ivanmatiashepam commented on mavenProj.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Please add this file to .gitignore and remove from git

2022-02-15 20:52 UTC, ivanmatiashepam commented on src/main/java/desktop/pages/BookDepositoryLoginPage.java
> +    public static String getStyleClearEmailButton() {
please make this method non-static. style of clear email button refers to some BookDepositoryLoginPage's object

2022-02-15 20:52 UTC, ivanmatiashepam commented on src/test/java/runner/TestRunner.java
> +        new BookDepositoryLoginPage(driver)
Please create a variable of BookDepositoryLoginPage inside each test and then getStyle for this variable (after you make that method non-static)

2022-02-15 20:52 UTC, ivanmatiashepam commented on src/test/java/runner/TestRunner.java
> +        Assert.assertEquals("display: block;", style);
Please add error message as a first argument to each assert

2022-02-15 20:52 UTC, ivanmatiashepam commented on src/test/java/runner/TestRunner.java
> +        driver = null;
what does this line do?

2022-02-15 20:52 UTC, ivanmatiashepam commented on src/main/java/driver/SingletonDriver.java
> +            System.setProperty(CHROME_DRIVER_EXE_PROPERTY, WEB_DRIVER_FILE_PATH);
please move these lines to the constructor of SingletonDriver and call it from here (new SingletonDriver();)

2022-02-16 08:02 UTC, Ivanenko16 commented on mavenProj.iml
> +<?xml version="1.0" encoding="UTF-8"?>
added to the .gitignore

2022-02-16 08:08 UTC, Ivanenko16 commented on src/main/java/desktop/pages/BookDepositoryLoginPage.java
> +    public static String getStyleClearEmailButton() {
fixed

2022-02-16 08:51 UTC, Ivanenko16 commented on src/test/java/runner/TestRunner.java
> +        new BookDepositoryLoginPage(driver)
fixed

2022-02-16 09:06 UTC, Ivanenko16 commented on src/main/java/driver/SingletonDriver.java
> +            System.setProperty(CHROME_DRIVER_EXE_PROPERTY, WEB_DRIVER_FILE_PATH);
fixed

2022-02-16 09:27 UTC, Ivanenko16 commented on src/test/java/runner/TestRunner.java
> +        driver = null;
105 row is delated

2022-02-16 13:09 UTC, ivanmatiashepam commented on src/main/java/driver/SingletonDriver.java
> +            System.setProperty(CHROME_DRIVER_EXE_PROPERTY, WEB_DRIVER_FILE_PATH);
please move next lines to the constructor as well. and in if-condition for getWebDriverInstance() method there should be only new SingletonDriver(); call

2022-02-17 11:30 UTC, merged